DROP TABLE BBS
CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_BBS;


--SEQ NUMBER(8) UNIQUE
 
--ID 글 작성자
--REF (시퀀스 넘버) STEP(그다음 칸) DEPTH(깊이) 답변요소

--DELL 삭제

CREATE TABLE BBS(
	SEQ NUMBER(8) PRIMARY KEY,
	ID VARCHAR2(50) NOT NULL,
	
	REF NUMBER(8) NOT NULL,
	STEP NUMBER(8) NOT NULL,
	DEPTH NUMBER(8) NOT NULL,
	
	TITLE VARCHAR2(200) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	WDATE DATE NOT NULL,
	
	DELL NUMBER(1) NOT NULL,
	READCOUNT NUMBER(8) NOT NULL
);

CREATE SEQUENCE SEQ_BBS
START WITH 1
INCREMENT BY 1;

ALTER TABLE BBS
ADD CONSTRAINT FK_BBS_ID FOREIGN KEY(ID)
REFERENCES MEMBER(ID);

SELECT * FROM BBS;
SELECT SEQ, ID, REF, STEP, DEPTH, TITLE, CONTENT, WDATE, DELL, READCOUNT 
FROM BBS
WHERE DELL=0
ORDER BY REF DESC, STEP ASC; 

UPDATE BBS 
SET TITLE=111, CONTENT=222
WHERE SEQ=22;

INSERT INTO BBS (SEQ, ID, REF, STEP, DEPTH, TITLE,
					CONTENT, WDATE, DELL, READCOUNT )
VALUES(SEQ_BBS.nextval,?,
(SELECT NVL(MAX(REF), 0)+1 FROM BBS)
,0,0,?,?,SYSDATE,0,0);
SELECT SEQ, ID, REF, STEP, DEPTH, TITLE, CONTENT, WDATE, DELL, READCOUNT
FROM BBS 
WHERE TITLE LIKE '%1%';


